// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Retegan_Andra_proiect2.Data;

namespace Retegan_Andra_proiect2.Migrations
{
    [DbContext(typeof(Retegan_Andra_proiect2Context))]
    [Migration("20220121203137_DataExam")]
    partial class DataExam
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Retegan_Andra_proiect2.Models.Catalog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataExam")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NotaStud")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("NumeStud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrenumeStud")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Catalog");
                });
#pragma warning restore 612, 618
        }
    }
}
