// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Retegan_Andra_proiect2.Data;

namespace Retegan_Andra_proiect2.Migrations
{
    [DbContext(typeof(Retegan_Andra_proiect2Context))]
    partial class Retegan_Andra_proiect2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Retegan_Andra_proiect2.Models.Catalog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataExam")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NotaStud")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("NumeStud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrenumeStud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfesorID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProfesorID");

                    b.ToTable("Catalog");
                });

            modelBuilder.Entity("Retegan_Andra_proiect2.Models.CatalogMaterie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CatalogID")
                        .HasColumnType("int");

                    b.Property<int>("MaterieID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CatalogID");

                    b.HasIndex("MaterieID");

                    b.ToTable("CatalogMaterie");
                });

            modelBuilder.Entity("Retegan_Andra_proiect2.Models.Materie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumeMaterie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Materie");
                });

            modelBuilder.Entity("Retegan_Andra_proiect2.Models.Profesor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumeProfesor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Profesor");
                });

            modelBuilder.Entity("Retegan_Andra_proiect2.Models.Catalog", b =>
                {
                    b.HasOne("Retegan_Andra_proiect2.Models.Profesor", "Profesor")
                        .WithMany("Cataloage")
                        .HasForeignKey("ProfesorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Retegan_Andra_proiect2.Models.CatalogMaterie", b =>
                {
                    b.HasOne("Retegan_Andra_proiect2.Models.Catalog", "Catalog")
                        .WithMany("CatalogMaterii")
                        .HasForeignKey("CatalogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retegan_Andra_proiect2.Models.Materie", "Materie")
                        .WithMany("CatalogMaterii")
                        .HasForeignKey("MaterieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
